version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/conformance"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/tests/e2e/scripts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/package"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/tests/integration"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/tests/terraform"
    schedule:
      interval: "weekly"
