# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 180

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 14

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels: []

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - internal
  - kind/bug
  - kind/bug-qa
  - kind/task
  - kind/feature
  - kind/enhancement
  - kind/design
  - kind/ci-improvements
  - kind/performance
  - kind/flaky-test
  - kind/documentation
  - kind/backport
  - priority/backlog
  - priority/critical-urgent
  - priority/important-longterm
  - priority/important-soon

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: true

# Label to use when marking as stale
staleLabel: status/stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This repository uses a bot to automatically label issues which have not had any activity (commit/comment/label) 
  for 180 days. This helps us manage the community issues better. If the issue is still relevant, please add a comment to the 
  issue so the bot can remove the label and we know it is still valid. If it is no longer relevant (or possibly fixed in the 
  latest release), the bot will automatically close the issue in 14 days. Thank you for your contributions.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Limit to only `issues`
only: issues
