ENV['VAGRANT_NO_PARALLEL'] = 'no'
NODE_ROLES = (ENV['NODE_ROLES'] ||
  ["server-0", "server-1", "server-2", "agent-0", "agent-1"])
NODE_BOXES = (ENV['NODE_BOXES'] ||
  ['generic/ubuntu2004', 'generic/ubuntu2004', 'generic/ubuntu2004', 'generic/ubuntu2004', 'generic/ubuntu2004'])
GITHUB_BRANCH = (ENV['GITHUB_BRANCH'] || "master")
NODE_CPUS = (ENV['NODE_CPUS'] || 2).to_i
NODE_MEMORY = (ENV['NODE_MEMORY'] || 1024).to_i
# Virtualbox >= 6.1.28 require `/etc/vbox/network.conf` for expanded private networks 
NETWORK_PREFIX = "10.10.10"

def provision(vm, roles, role_num, node_num)
  vm.box = NODE_BOXES[node_num]
  vm.hostname = "#{roles[0]}-#{role_num}"
  # An expanded netmask is required to allow VM<-->VM communication, virtualbox defaults to /32
  vm.network "private_network", ip: "#{NETWORK_PREFIX}.#{100+node_num}", netmask: "255.255.255.0"

  osConfigure(vm)
  
  # Grabs the last 5 commit SHA's from the given branch, then purges any commits that do not have a passing CI build
  $check_commit = <<-'SCRIPT'
  curl -s -H 'Accept: application/vnd.github.v3+json' 'https://api.github.com/repos/k3s-io/k3s/commits?per_page=5&sha=#{GITHUB_BRANCH}' | jq -r '.[] | .sha'  &> /tmp/k3s_commits
  curl -s --fail https://storage.googleapis.com/k3s-ci-builds/k3s-$(head -n 1 /tmp/k3s_commits).sha256sum
  while [ $? -ne 0 ]; do
    sed -i 1d /tmp/k3s_commits
    curl -s --fail https://storage.googleapis.com/k3s-ci-builds/k3s-$(head -n 1 /tmp/k3s_commits).sha256sum
  done
  SCRIPT
  vm.provision "shell",
    inline: $check_commit
    
  vm.provision "shell", inline: "ping -c 2 k3s.io"
  
  if roles.include?("server") && role_num == 0
    vm.provision 'k3s-install', type: 'k3s', run: 'once' do |k3s|
      k3s.installer_url = 'https://get.k3s.io'
      k3s.args = %W[server --cluster-init --node-external-ip=#{NETWORK_PREFIX}.100 --flannel-iface=eth1]
      k3s.env = %W[K3S_KUBECONFIG_MODE=0644 K3S_TOKEN=vagrant INSTALL_K3S_COMMIT=$(head\ -n\ 1\ /tmp/k3s_commits)]
      k3s.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
    end
  elsif roles.include?("server") && role_num != 0
    vm.provision 'k3s-install', type: 'k3s', run: 'once' do |k3s|
      k3s.installer_url = 'https://get.k3s.io'
      k3s.args = %W[server --server https://#{NETWORK_PREFIX}.100:6443 --flannel-iface=eth1]
      k3s.env = %W[K3S_KUBECONFIG_MODE=0644 K3S_TOKEN=vagrant INSTALL_K3S_COMMIT=$(head\ -n\ 1\ /tmp/k3s_commits)]
      k3s.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
    end
  end
  if roles.include?("agent")
    vm.provision 'k3s-install', type: 'k3s', run: 'once' do |k3s|
      k3s.installer_url = 'https://get.k3s.io'
      k3s.args = %W[agent --server https://#{NETWORK_PREFIX}.100:6443 --flannel-iface=eth1]
      k3s.env = %W[K3S_KUBECONFIG_MODE=0644 K3S_TOKEN=vagrant INSTALL_K3S_COMMIT=$(head\ -n\ 1\ /tmp/k3s_commits)]
      k3s.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
    end
  end
  if vm.box.include?("microos")
    vm.provision 'k3s-reload', type: 'reload', run: 'once'
  end
end

def osConfigure(vm)

  if vm.box.include?("ubuntu2004")
    vm.provision "shell", inline: "systemd-resolve --set-dns=8.8.8.8 --interface=eth0"
    vm.provision "shell", inline: "apt install -y jq"
  end
  if vm.box.include?("Leap")
    vm.provision "shell", inline: "zypper install -y jq"
  end
  if vm.box.include?("microos")
    vm.provision "shell", inline: "transactional-update pkg install -y jq", reboot: true
  end

end

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-k3s", "vagrant-reload"]
  # Default provider is libvirt, virtualbox is only provided as a backup
  config.vm.provider "libvirt" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
  end
  
  if NODE_ROLES.kind_of?(String)
    NODE_ROLES = NODE_ROLES.split(" ", -1)
  end
  if NODE_BOXES.kind_of?(String)
    NODE_BOXES = NODE_BOXES.split(" ", -1)
  end

  # Must iterate on the index, vagrant does not understand iterating 
  # over the node roles themselves
  NODE_ROLES.length.times do |i|
    name = NODE_ROLES[i]
    config.vm.define name do |node|
      roles = name.split("-", -1)
      role_num = roles.pop.to_i
      provision(node.vm, roles, role_num, i)
    end
  end
end
