ARG GOLANG=golang:1.19.6-alpine3.17
FROM ${GOLANG}

RUN apk -U --no-cache add bash jq
ENV DAPPER_SOURCE /go/src/github.com/k3s-io/k3s/
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

COPY ./scripts/test-mods /bin/

ENTRYPOINT ["/bin/test-mods"]
