ARG GOLANG=golang:1.18.1-alpine3.15
FROM ${GOLANG}

RUN apk -U --no-cache add bash jq
ENV DAPPER_SOURCE /go/src/github.com/k3s-io/k3s/
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

COPY ./scripts/test-mods /bin/

ENTRYPOINT ["/bin/test-mods"]
