FROM golang:1.13.3-alpine3.10

RUN apk -U --no-cache add bash git gcc musl-dev docker curl jq coreutils
RUN SONOBUOY_VER=v0.16.2 && \
    SONOBUOY_PKG=github.com/vmware-tanzu/sonobuoy && \
    go get -d ${SONOBUOY_PKG} && \
    cd /go/src/${SONOBUOY_PKG} && \
    git checkout -b current ${SONOBUOY_VER} && \
    go build -o /usr/local/bin/sonobuoy
RUN rm -rf /go/src /go/pkg

ARG DAPPER_HOST_ARCH
ENV ARCH $DAPPER_HOST_ARCH

RUN curl -sL https://storage.googleapis.com/kubernetes-release/release/$( \
            curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt \
        )/bin/linux/${ARCH}/kubectl -o /usr/local/bin/kubectl && \
    chmod a+x /usr/local/bin/kubectl

ENV DAPPER_RUN_ARGS --privileged --network host
ENV DAPPER_ENV REPO TAG DRONE_TAG IMAGE_NAME
ENV DAPPER_SOURCE /go/src/github.com/rancher/k3s/
ENV DAPPER_OUTPUT ./dist
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry.sh"]
CMD ["sonobuoy-e2e-tests"]
