---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gateway-api-crd
  namespace: kube-system
spec:
  forceConflicts: true
  failurePolicy: retry
  takeOwnership: true
  chart: https://%{KUBERNETES_API}%/static/charts/gateway-api-crd-1.6.102.tgz
