FROM golang:buster

# Enables integration tests to run on existing cluster via Sonobuoy plugin

RUN apt update && \
    apt install -y --no-install-recommends git lsof bash openssh-server gcc g++ make ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR $GOPATH/src/github.com/k3s-io/k3s-io/k3s/

COPY ./tests/testdata ./testdata
COPY ./tests/integration/test-runner.sh .
COPY ./dist/artifacts/k3s /usr/local/bin
COPY ./dist/artifacts/k3s-integration-* ./tests/

RUN go install github.com/onsi/ginkgo/v2/ginkgo@v2.17.1
RUN go install github.com/onsi/gomega@v1.32.0