FROM golang:buster


RUN apt update && \
    apt install -y curl git bash openssh-server gcc g++ make ca-certificates && \
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

WORKDIR $GOPATH/src/github.com/rancher/k3s-io/k3s/

COPY ./tests/testdata ./testdata
COPY ./dist/artifacts/k3s /usr/local/bin
COPY ./dist/artifacts/k3s-integration-* ./tests/

RUN go get -u github.com/onsi/gomega
RUN go get -u github.com/onsi/ginkgo
