#!/bin/bash
set -ve

download_go
# ---
cat <<EOF >/etc/profile.d/build.sh
export SELINUX=true
# export STATIC_BUILD=true
EOF
. /etc/profile.d/build.sh
# ---
apt-get update
apt-get install -y \
  build-essential \
  ca-certificates \
  curl \
  docker.io \
  gcc \
  git \
  jq \
  libffi-dev \
  libseccomp-dev \
  libsqlite3-dev \
  libselinux1-dev \
  libuv1-dev \
  make \
  npm \
  pkg-config \
  python3 \
  squashfs-tools \
  tar \
  wget \
  vim \
  zip \
  zlib1g-dev \
  zstd

# ---
go install -u github.com/go-delve/delve/cmd/dlv
# ---
