#!/bin/bash

set -e

cd $(dirname $0)/..

. ./scripts/version.sh

. ./scripts/env-common.sh
. ./scripts/env-traefik.sh

export TZ=UTC

umask 022
mkdir -p ${CHARTS_DIR}
mkdir -p ${DATA_DIR}

mkdir -p bin/aux
if [ -z "$SKIP_BUILDROOT" ]; then
  curl --compressed -sfL https://github.com/k3s-io/k3s-root/releases/download/${VERSION_ROOT}/k3s-root-${ARCH}.tar | tar xf - --exclude=bin/socat
fi

git clone --single-branch --branch=${VERSION_RUNC} --depth=1 https://github.com/opencontainers/runc ${RUNC_DIR}

git clone --single-branch --branch=${VERSION_CONTAINERD} --depth=1 https://github.com/k3s-io/containerd ${CONTAINERD_DIR}

git clone -b $VERSION_CNIPLUGINS https://github.com/rancher/plugins.git $CNI_PLUGINS_DIR

curl -sfL ${TRAEFIK_URL} -o ${CHARTS_DIR}/${TRAEFIK_FILE}

cp scripts/wg-add.sh bin/aux/
