#!/bin/bash
set -e

source $(dirname $0)/version.sh

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}
IMAGE_NAME=${IMAGE_NAME:-k3s}

IMAGE=${REPO}/${IMAGE_NAME}:${TAG}
docker build -t ${IMAGE} -f package/Dockerfile .
echo Built ${IMAGE}
