#!/bin/bash

cd $(dirname $0)/..

. ./scripts/version

mkdir -p dist/artifacts

tar cvzf dist/artifacts/rio-${VERSION}-linux-amd64.tar.gz -h bin/rio --xform='s!^bin!rio-'${VERSION}'-linux-amd64!'
tar cvzf dist/artifacts/rio-${VERSION}-darwin.tar.gz bin/rio-darwin --xform='s!.*!rio-'${VERSION}'-darwin/rio!'

W=rio-${VERSION}-windows
mkdir -p $W
trap "rm -rf $W" EXIT

cp -f bin/rio-windows $W/rio.exe
zip dist/artifacts/rio-${VERSION}-windows.zip $W/rio.exe
