#!/bin/bash

export NUM_SERVERS=1
export NUM_AGENTS=1
export SERVER_ARGS='--no-deploy=traefik'
export WAIT_SERVICES='coredns local-path-provisioner metrics-server'

export sonobuoyParallelArgs=(--e2e-focus='\[Conformance\]' --e2e-skip='\[Serial\]' --e2e-parallel=y)
export sonobuoySerialArgs=(--e2e-focus='\[Serial\].*\[Conformance\]')

start-test() {
  sonobuoy-test $@
}
export -f start-test

test-post-hook() {
  if [[ $1 -eq 0 ]]; then
    return
  fi
  local flakyTest1='\[Fail\] \[sig-node\] Probing container \[It\] should have monotonically increasing restart count \[NodeConformance\] \[Conformance\]'
  local flakyTest2='\[Fail\] \[sig-node\] Pods \[It\] should delete a collection of pods \[Conformance\]'
  grep -sqF -e $flakyTest1 -e $flakyTest2 $TEST_DIR/sonobuoy/plugins/e2e/results/global/e2e.log
}
export -f test-post-hook