#!/bin/bash
set -e -x

cd $(dirname $0)/..

. ./scripts/build-common-env-vars.sh

# Overwrite variables
LDFLAGS="
    -w -s"
STATIC=""
TAGS="netcgo osusergo providerless"

# Sanity check for downstream dependencies
echo 'Validate K3s cross-compilation on Windows x86_64' 
GOOS=windows CGO_ENABLED=1 CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc \
    "${GO}" build -tags "${TAGS}" -ldflags "${VERSIONFLAGS} ${LDFLAGS} ${STATIC}" -o bin/k3s.exe ./cmd/server/main.go

if [ "${KEEP_WINDOWS_BIN}" != 'true' ]; then
    rm -rf bin/k3s.exe
fi
