#!/bin/bash
set -e

cd $(dirname $0)/..

if ! command -v golangci-lint; then
    echo Skipping validation: no golangci-lint available
    exit
fi
echo Running validation

if [ ! -e build/data ];then
    mkdir -p build/data
fi

echo Running: go generate
go generate

echo Running: golangci-lint
golangci-lint run

. ./scripts/version.sh

if [ -n "$DIRTY" ]; then
    echo Source dir is dirty
    git status --porcelain --untracked-files=no
    exit 1
fi
