name: Lint Action Workflows
on:
  pull_request:
    paths:
      - ".github/workflows/*"

permissions:
  contents: read
  
jobs:
  acitonlint:
    name: Lint GitHub Workflows
    runs-on: ubuntu-latest # Runs on standard runner, docker pulls with --platform
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - name: actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2
        with:
          shellcheck: false
          pyflakes: false
          cache: ${{ github.ref == 'refs/heads/main' }}

