name: Airgap Image Tarballs
on:
  pull_request:
    paths:
      - "scripts/package-airgap"
      - "scripts/airgap/image-list.txt"
      - ".github/workflows/airgap.yaml"
  workflow_call: {}

permissions:
  contents: read

jobs:
  build-airgap:
    name: Export Images (${{ matrix.arch }})
    runs-on: ubuntu-latest # Runs on standard runner, docker pulls with --platform
    strategy:
      matrix:
        arch: [amd64, arm64, arm]

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Set up Docker
        uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5
        with:
          version: type=image,tag=28
          daemon-config: '{"features":{"containerd-snapshotter":true}}'
          set-host: true
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Install Dependencies
        run: sudo apt-get update -y && sudo apt-get install -y zstd pigz

      - name: Create Airgap Package
        run: |
          mkdir -p ./dist/artifacts
          export CONTAINERD_ADDRESS=$(docker info --format '{{.Containerd.Address}}')
          sudo chgrp $(id -g) $CONTAINERD_ADDRESS $(dirname $CONTAINERD_ADDRESS)
          ./scripts/package-airgap ${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: images-${{ matrix.arch }}
          path: dist/artifacts/k3s-airgap-images-${{ matrix.arch }}.*
          if-no-files-found: error
          retention-days: 7
