name: Integration Test Coverage
on: 
  workflow_dispatch: {}

permissions:
  contents: read

env:
  GOCOVERDIR: /tmp/k3scov
  
jobs:
  build:
    uses: ./.github/workflows/build-k3s.yaml
    with:
      arch: arm64
  itest:
    needs: build
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Install Go
      uses: ./.github/actions/setup-go
    - name: "Download k3s binary"
      uses: actions/download-artifact@v4
      with:
        name: k3s
        path: ./dist/artifacts
    - name: Launch Debug Session
      uses: dereknola/action-upterm@v1.1
      with:
        ## If no one connects after 5 minutes, shut down server.
        wait-timeout-minutes: 5