name: Update epics
on:
  issues:
    types: [opened, closed, reopened]

permissions:
  contents: read
  
jobs:
  epics:
    runs-on: ubuntu-latest
    name: Update epic issues
    permissions:
      issues: write
    steps:
      - name: Run epics action
        uses: cloudaper/epics-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          epic-label-name: epic
          auto-close-epic: false