name: Nightly Conformance
on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch: {}
  push: {}

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-k3s.yaml
    with:
      upload-image: true
  test:
    name: Conformance
    runs-on: ${{ github.repository_owner == 'k3s-io' && matrix.suite == 'parallel' && 'cncf-ubuntu-8-32-x86' || 'ubuntu-24.04' }}
    needs: build
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, etcd, mysql, postgres]
        suite: [serial, parallel]
    steps:
      - name: Remove Unnecessary Tools
        if: runner.environment == 'github-hosted'
        working-directory: /
        run: |
          sudo rm -rf \
            /home/linuxbrew \
            /home/packer \
            /opt/az \
            /opt/microsoft \
            /usr/lib/firefox \
            /usr/lib/google-cloud-sdk \
            /usr/local/julia* \
            /usr/local/share/boost \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/az* \
            /usr/share/dotnet \
            /usr/share/miniconda \
            /usr/share/swift
          df -khl
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: {fetch-depth: 1}
      - name: "Download K3s image"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: k3s-amd64
          path: ./dist/artifacts
      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5
        with:
          version: type=image,tag=28
          set-host: true
      - name: Install Go
        uses: ./.github/actions/setup-go
      - name: Load and set K3s image
        run: |
          chmod +x ./dist/artifacts/k3s
          docker image load -i ./dist/artifacts/k3s-image.tar
          IMAGE_TAG=$(docker image ls --format '{{.Repository}}:{{.Tag}}' | grep 'rancher/k3s')
          echo "K3S_IMAGE=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Run ${{ matrix.db }} ${{ matrix.suite}} Conformance Test
        run: go test -timeout=45m ./tests/docker/conformance/conformance_test.go -k3sImage="$K3S_IMAGE" -db ${{ matrix.db }} ${{ matrix.suite == 'serial' && '-serial' || '' }} -ginkgo.v -ci
